npcs:
  '3': "tutbot01"
  '4': "tutbot02"
  '5': "tutbot03"
  '7': "tutbot04"
  '8': "tutbot05"
  '9': "tutbot06"
  '10': "tutbot07"
  '14': "tutbot08"
  '15': "tutbot09"
  '16': "tutbot10"
  '19': "tutbot11"
  '20': "tutbot12"
  '26': "tutbot13"
  '27': "tutbot14"
  '28': "tutbot15"
  '31': "tutbot16"
  '33': "tutbot17"
  '34': "tutbot18"
  '35': "tutbot19"
  '37': "tutbot20"
  '47': "tutbot21"
  '93': "tutbot22"
  '39': "certbot"
  '6': "navbot"
  '24': "navbot"
  '23': "navbot"
  '22': "navbot"
  '30': "navbot"
  '38': "navbot"
  '44': "navbot"
  '45': "navbot"
