npcs:
  '40': "flynn_bart"

variables:
    quest_name: "Cheth Collector"
    quester_name: "flynn_bart"
    journal_headline: "$default.journal_head_prefix$$quest_name$$default.journal_head_suffix$"

journal_main_page:
    can_started:
        priority: 2
        text: '  $default.journal_status_1$$quest_name$'
        conditions: '!cond_acc,!cond_done'
    started:
        priority: 1
        text: '  $default.journal_status_2$$quest_name$'
        conditions: 'cond_acc,!cond_done'
    finished:
        priority: 3
        text: '  $default.journal_status_3$$quest_name$'
        conditions: 'cond_done'

cancel:
  chethCollector:
    name: "Cheth Collector"
    conditions: "cond_acc,!cond_done"
    objectives: "obj_mine_cheth"
    tags: "tag_acc"
    journal: "journal_start,journal_return"