npcs:
  '40': "flynnBart"

variables:
    quest_name: "Cheth Collector"
    quester_name: "flynnBart"
    journal_headline: "$default.journal_head_prefix$$quest_name$$default.journal_head_suffix$"

journal_main_page:
    can_started:
        priority: 2
        text: '  $default.journal_status_1$$quest_name$'
        conditions: '!cheth_collector_cond_acc,!cheth_collector_cond_done'
    started:
        priority: 1
        text: '  $default.journal_status_2$$quest_name$'
        conditions: 'cheth_collector_cond_acc,!cheth_collector_cond_done'
    finished:
        priority: 3
        text: '  $default.journal_status_3$$quest_name$'
        conditions: 'cheth_collector_cond_done'

